# Generated by Django 2.2.3 on 2020-05-14 23:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messages',
            managers=[
                ('objectes', django.db.models.manager.Manager()),
            ],
        ),
    ]
