# Generated by Django 2.2.3 on 2020-05-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200515_0001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='messages',
            managers=[
            ],
        ),
    ]
